"""session cookies

Revision ID: 2e4f852e78af
Revises: d0f13117205c
Create Date: 2024-06-10 17:13:07.044184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e4f852e78af'
down_revision: Union[str, None] = 'd0f13117205c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('session_token', sa.String(length=150), nullable=True))
    op.create_unique_constraint(None, 'user', ['session_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'session_token')
    # ### end Alembic commands ###
